baseURL = 'https://rma.st/'
languageCode = 'en-us'
title = 'Ryan Mast'
theme = 'hugo-xmin'

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Contact Me"
url = "/contact"
weight = 2
